site_name: UF Autonomy Park - Wiki
theme:
  name: material
  favicon: images/favicon.ico
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
plugins:
  - mkdocs-pdf
markdown_extensions:
  - pymdownx.pathconverter:
      base_path: 'apark-wiki' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'